name: "Terraform Managed Orchestration"

on:
  push:
    branches:
      - main
  # This adds the manual button in the Actions tab
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Action: apply or destroy'
        required: true
        default: 'apply'
        type: choice
        options:
        - apply
        - destroy

jobs:
  terraform:
    name: "Terraform Engine"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "ap-south-1"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      # Logic: Runs 'apply' if pushed or if 'apply' is selected manually
      - name: Terraform Apply
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'apply')
        run: terraform apply -auto-approve

      # Logic: Runs 'destroy' ONLY if 'destroy' is selected manually
      - name: Terraform Destroy
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve